/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qasonar;
import java.io.BufferedReader;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qasonar extends AbstractQasonar { 
	protected BufferedReader readerC;
	protected String distance = ""; //d(  distance  )
	protected int counter = 1;
	
	public Qasonar(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	public void startSonarC(){
  		try {
  	  		//Execute a C program that generates the sonar values
			Process p = Runtime.getRuntime().exec("sudo ./SonarAlone");
			readerC   = new BufferedReader(new java.io.InputStreamReader(p.getInputStream()));
			println("Process in C STARTED "  +  readerC);
		} catch (Exception e) {
 			e.printStackTrace();
		}		
	}	
	public String getDistanceFromSonar(){
		try {
			String inpS = readerC.readLine();
			distance = "data( "+ counter++ + ", distance, d("+inpS+") )";  
			return distance;
		} catch (Exception e) {
 			e.printStackTrace();
 			return "data( "+ counter++ + ", distance, d(0) )"; 
		}
	}	
}
