/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qacontrol;
import it.unibo.is.interfaces.IActivity;
import it.unibo.is.interfaces.IIntent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qacontrol extends AbstractQacontrol implements IActivity { 
	
	private int count;
	
	public Qacontrol(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
		count=0;
	}
	public void createAButtonWithGui(){
		outEnvView.getEnv().addCmdPanel("btn", new String[]{"click"}, this);
	}
	
	public void execAction(String cmd) {
		try {
			//messaggi
			//sendMsg("turn","qacontrol", QActorContext.dispatch, "switch(1)" );
			//eventi
			this.emit("localclick", "clicked(" + count++ +")");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	@Override
	public void execAction() {
		// TODO Auto-generated method stub
		
	}
	@Override
	public void execAction(IIntent input) {
		// TODO Auto-generated method stub
		
	}
	@Override
	public String execActionWithAnswer(String cmd) {
		// TODO Auto-generated method stub
		return null;
	}
}
