/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.mybutton;
import java.awt.Button;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Mybutton extends AbstractMybutton { 
	
	private IButton button;
	
	public Mybutton(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public void createGuiButton(int pinNum, String command){
		button = new ButtonWithGui(this, command, pinNum);
		outEnvView.getEnv().addPanel((Button) button);
	}
	
	public void createPi4jButton(int pinNum, String command){
		button = new ButtonWithRasp(this, outEnvView, pinNum, command);
	}
}
