/* Generated by AN DISI Unibo */ 
package it.unibo.rover;
import alice.tuprolog.SolveInfo;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.ActionReceiveTimed;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.iot.configurator.Configurator;
import it.unibo.iot.executors.baseRobot.IBaseRobot; 
import it.unibo.iot.models.sensorData.distance.IDistanceSensorData;
import it.unibo.iot.models.sensorData.impact.IImpactSensorData;
import it.unibo.iot.models.sensorData.line.ILineSensorData;
import it.unibo.iot.models.sensorData.magnetometer.IMagnetometerSensorData;
import it.unibo.iot.sensors.ISensor; 
import it.unibo.iot.sensors.ISensorObserver;
import it.unibo.iot.sensors.distanceSensor.DistanceSensor;
import it.unibo.iot.sensors.impactSensor.ImpactSensor;
import it.unibo.iot.sensors.lineSensor.LineSensor;
import it.unibo.iot.sensors.magnetometerSensor.MagnetometerSensor;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.QActorMessage;
import it.unibo.qactors.QActorUtils;


class QaRobotActor extends it.unibo.qactor.robot.RobotActor{
	public QaRobotActor(
		String name, QActorContext ctx, String worldTheoryPath,
			IOutputEnvView outEnvView, String baserobot, String defaultPlan )  throws Exception{
		super(name, ctx, "./srcMore/it/unibo/rover/plans.txt", worldTheoryPath,
		outEnvView, it.unibo.qactor.robot.RobotSysKb.setRobotBase(ctx, baserobot) , defaultPlan);
	}
}

public class AbstractRover extends QaRobotActor { 
protected AsynchActionResult aar = null;
protected boolean actionResult = true;
protected alice.tuprolog.SolveInfo sol;
//protected IMsgQueue mysupport ;  //defined in QActor
protected String planFilePath    = null;
protected String terminationEvId = "default";
protected String parg="";
protected boolean bres=false;
protected IActorAction  action;

		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}


	public AbstractRover(String actorId, QActorContext myCtx, IOutputEnvView outEnvView ,String baserobot)  throws Exception{
		super(actorId, myCtx,  
		"./srcMore/it/unibo/rover/WorldTheory.pl",
		setTheEnv( outEnvView ) ,baserobot , "init");		
		this.planFilePath = "./srcMore/it/unibo/rover/plans.txt";
		//Plan interpretation is done in Prolog
		//if(planFilePath != null) planUtils.buildPlanTable(planFilePath);
 	}
	@Override
	protected void doJob() throws Exception {
		String name  = getName().replace("_ctrl", "");
		mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
 		initSensorSystem();
		boolean res = init();
		//println(getName() + " doJob " + res );
		QActorContext.terminateQActorSystem(this);
	} 
	/* 
	* ------------------------------------------------------------
	* PLANS
	* ------------------------------------------------------------
	*/
    public boolean init() throws Exception{	//public to allow reflection
    try{
    	int nPlanIter = 0;
    	//curPlanInExec =  "init";
    	boolean returnValue = suspendWork;		//MARCHH2017
    while(true){
    	curPlanInExec =  "init";	//within while since it can be lost by switchlan
    	nPlanIter++;
    		temporaryStr = "\"rover STARTS\"";
    		println( temporaryStr );  
    		//parg = "actorOp(workWithUnity(\"192.168.137.1\"))"; //JUNE2017
    		parg = "workWithUnity(\"192.168.137.1\")";
    		//ex solveGoalReactive JUNE2017
    		aar = actorOpExecuteReactive(parg,3600000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "init";
    			if( aar.getTimeRemained() <= 0 ) addRule("tout(actorOp,"+getName()+")");
    			if( ! aar.getGoon() ) break;
    		} 			
    		else{
    		//Store actorOpDone with the result
    		 	String gg = "storeActorOpResult( X, Y )".replace("X", parg).replace("Y",aar.getResult() );
    		 	//System.out.println("actorOpExecute gg=" + gg );
    			 	 	pengine.solve(gg+".");			
    		}
    		
    		//parg = "actorOp(createSimulatedActor)"; //JUNE2017
    		parg = "createSimulatedActor";
    		//ex solveGoalReactive JUNE2017
    		aar = actorOpExecuteReactive(parg,3600000,"","");
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "init";
    			if( aar.getTimeRemained() <= 0 ) addRule("tout(actorOp,"+getName()+")");
    			if( ! aar.getGoon() ) break;
    		} 			
    		else{
    		//Store actorOpDone with the result
    		 	String gg = "storeActorOpResult( X, Y )".replace("X", parg).replace("Y",aar.getResult() );
    		 	//System.out.println("actorOpExecute gg=" + gg );
    			 	 	pengine.solve(gg+".");			
    		}
    		
    		if( ! planUtils.switchToPlan("someMove").getGoon() ) break;
    		if( ! planUtils.switchToPlan("handlecommands").getGoon() ) break;
    		//delay
    		aar = delayReactive(6000000,"" , "");
    		if( aar.getInterrupted() ) curPlanInExec   = "init";
    		if( ! aar.getGoon() ) break;
    		temporaryStr = "\"rover ENDS\"";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=init WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean someMove() throws Exception{	//public to allow reflection
    try{
    	int nPlanIter = 0;
    	//curPlanInExec =  "someMove";
    	boolean returnValue = suspendWork;		//MARCHH2017
    while(true){
    	curPlanInExec =  "someMove";	//within while since it can be lost by switchlan
    	nPlanIter++;
    		temporaryStr = "\"rover robotForward \"";
    		println( temporaryStr );  
    		temporaryStr = "\"rover robotRight \"";
    		println( temporaryStr );  
    		//right
    		//if( ! execRobotMove("someMove","right",80,0,100, "sonarDetect,alarm,usercmd" , "handleobstacle,handleAlarm,controlToUser") ) break;
    		    aar = execRobotMove("someMove","right",80,0,100, "sonarDetect,alarm,usercmd" , "handleobstacle,handleAlarm,controlToUser");
    		    if( aar.getInterrupted() ){
    		    	curPlanInExec   = "someMove";
    		    	if( ! aar.getGoon() ) break;
    		    } 			
    		if( planUtils.repeatPlan(nPlanIter,1).getGoon() ) continue;
    		returnValue = continueWork;  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=someMove WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean controlToUser() throws Exception{	//public to allow reflection
    try{
    	int nPlanIter = 0;
    	//curPlanInExec =  "controlToUser";
    	boolean returnValue = suspendWork;		//MARCHH2017
    while(true){
    	curPlanInExec =  "controlToUser";	//within while since it can be lost by switchlan
    	nPlanIter++;
    		temporaryStr = "\"rover controlToUser\"";
    		println( temporaryStr );  
    		if( ! planUtils.switchToPlan("execRobotCommand").getGoon() ) break;
    		if( ! planUtils.switchToPlan("handlecommands").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=controlToUser WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean handlecommands() throws Exception{	//public to allow reflection
    try{
    	int nPlanIter = 0;
    	//curPlanInExec =  "handlecommands";
    	boolean returnValue = suspendWork;		//MARCHH2017
    while(true){
    	curPlanInExec =  "handlecommands";	//within while since it can be lost by switchlan
    	nPlanIter++;
    		temporaryStr = "\"rover waits for user commands\"";
    		println( temporaryStr );  
    		//senseEvent
    		aar = planUtils.senseEvents( 100000,"usercmd","execRobotCommand",
    		"sonarDetect,alarm" , "handleobstacle,handleAlarm",ActionExecMode.synch );
    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
    			//println("			WARNING: sense timeout");
    			addRule("tout(senseevent,"+getName()+")");
    		}
    		if( planUtils.repeatPlan(nPlanIter,0).getGoon() ) continue;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=handlecommands WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean execRobotCommand() throws Exception{	//public to allow reflection
    try{
    	int nPlanIter = 0;
    	//curPlanInExec =  "execRobotCommand";
    	boolean returnValue = suspendWork;		//MARCHH2017
    while(true){
    	curPlanInExec =  "execRobotCommand";	//within while since it can be lost by switchlan
    	nPlanIter++;
    		printCurrentEvent(false);
    		//onEvent
    		if( currentEvent.getEventId().equals("usercmd") ){
    		 		String parg = "actorOp(execCmdGui(CMD))";
    		 		/* ActorOp */
    		 		parg =  updateVars( Term.createTerm("usercmd(robotgui(CMD))"), Term.createTerm("usercmd(CMD)"), 
    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
    		 		if( parg != null ){
    		 			aar = solveGoalReactive(parg,3600000,"sonarDetect,alarm,usercmd","handleobstacle,handleAlarm,handleUserCommand");
    		 			//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		 			if( aar.getInterrupted() ){
    		 				curPlanInExec   = "execRobotCommand";
    		 				if( aar.getTimeRemained() <= 0 ) addRule("tout(actorOp,"+getName()+")");
    		 				if( ! aar.getGoon() ) break;
    		 			} 			
    		 		}
    		 }
    		returnValue = continueWork;  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=execRobotCommand WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean handleobstacle() throws Exception{	//public to allow reflection
    try{
    	int nPlanIter = 0;
    	//curPlanInExec =  "handleobstacle";
    	boolean returnValue = suspendWork;		//MARCHH2017
    while(true){
    	curPlanInExec =  "handleobstacle";	//within while since it can be lost by switchlan
    	nPlanIter++;
    		//playsound
    		terminationEvId = "endplay";
    			 	aar = playSound("./audio/tada2.wav",ActionExecMode.asynch, terminationEvId, 2000,"" , "" ); 
    				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    				if( aar.getInterrupted() ){
    					curPlanInExec   = "handleobstacle";
    					if( aar.getTimeRemained() <= 0 ) addRule("tout(Sound,"+getName()+")");
    					if( ! aar.getGoon() ) break;
    				} 			
    		//backward
    		//if( ! execRobotMove("handleobstacle","backward",90,0,1000, "" , "") ) break;
    		    aar = execRobotMove("handleobstacle","backward",90,0,1000, "" , "");
    		    if( aar.getInterrupted() ){
    		    	curPlanInExec   = "handleobstacle";
    		    	if( ! aar.getGoon() ) break;
    		    } 			
    		returnValue = continueWork;  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=handleobstacle WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean handleAlarm() throws Exception{	//public to allow reflection
    try{
    	int nPlanIter = 0;
    	//curPlanInExec =  "handleAlarm";
    	boolean returnValue = suspendWork;		//MARCHH2017
    while(true){
    	curPlanInExec =  "handleAlarm";	//within while since it can be lost by switchlan
    	nPlanIter++;
    		temporaryStr = "\"ALARM\"";
    		println( temporaryStr );  
    		//playsound
    		terminationEvId = "endPlay";
    			 	aar = playSound("./audio/computer_complex3.wav",ActionExecMode.asynch, terminationEvId, 3000,"" , "" ); 
    				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    				if( aar.getInterrupted() ){
    					curPlanInExec   = "handleAlarm";
    					if( aar.getTimeRemained() <= 0 ) addRule("tout(Sound,"+getName()+")");
    					if( ! aar.getGoon() ) break;
    				} 			
    		//stop
    		//if( ! execRobotMove("handleAlarm","stop",10,0,0, "" , "") ) break;
    		    aar = execRobotMove("handleAlarm","stop",10,0,0, "" , "");
    		    if( aar.getInterrupted() ){
    		    	curPlanInExec   = "handleAlarm";
    		    	if( ! aar.getGoon() ) break;
    		    } 			
    		returnValue = continueWork;  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=handleAlarm WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    public boolean handleUserCommand() throws Exception{	//public to allow reflection
    try{
    	int nPlanIter = 0;
    	//curPlanInExec =  "handleUserCommand";
    	boolean returnValue = suspendWork;		//MARCHH2017
    while(true){
    	curPlanInExec =  "handleUserCommand";	//within while since it can be lost by switchlan
    	nPlanIter++;
    		//stop
    		//if( ! execRobotMove("handleUserCommand","stop",10,0,0, "" , "") ) break;
    		    aar = execRobotMove("handleUserCommand","stop",10,0,0, "" , "");
    		    if( aar.getInterrupted() ){
    		    	curPlanInExec   = "handleUserCommand";
    		    	if( ! aar.getGoon() ) break;
    		    } 			
    		returnValue = continueWork;  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
       //println( getName() + " plan=handleUserCommand WARNING:" + e.getMessage() );
       QActorContext.terminateQActorSystem(this); 
       return false;  
    }
    }
    /* 
    * ------------------------------------------------------------
    * SENSORS
    * ------------------------------------------------------------
    */
    protected void initSensorSystem(){		
    	try {
    		String goal = "consult( \"./src/it/unibo/rover/sensorTheory.pl\" )";
    		SolveInfo sol = QActorUtils.solveGoal( goal ,pengine );
    		if( ! sol.isSuccess() ){
    			//println( "avatar initSensorSystem attempt to load sensorTheory "  );
    			goal = "consult( \"./sensorTheory.pl\" )";
    			QActorUtils.solveGoal( pengine, goal  );
    			//println( "avatar initSensorSystem= "  +  aar.getResult() );
    		}
    		addSensorObservers();
    	} catch (Exception e) {
    		e.printStackTrace();
    	}
    }
    /*
    //COMPONENTS
     RobotComponent motorleft 
     RobotComponent motorright 
    sensor distanceFront  todo  
    Composed component motors
    */
    protected void addSensorObservers(){
    	for (ISensor<?> sensor : Configurator.getInstance().getSensors()) {
    		//println( "rover sensor= "  + sensor.getDefStringRep() );
    		//println( "rover sensor class= "  + sensor.getClass().getName() );
        	if( sensor instanceof DistanceSensor){
        		DistanceSensor sensorDistance  = (DistanceSensor) sensor;
        		ISensorObserver<IDistanceSensorData> obs = new SensorObserver<IDistanceSensorData>(this,outEnvView);
        //		println( "avatar add observer to  "  + sensorDistance.getDefStringRep() );
        		sensorDistance.addObserver(  obs  ) ;
        	}
        	if( sensor instanceof LineSensor){
        		LineSensor sensorLine = (LineSensor) sensor;
         		ISensorObserver<ILineSensorData> obs = new SensorObserver<ILineSensorData>(this,outEnvView);
        //		println( "avatar add observer to  "  + sensorLine.getDefStringRep() );
        		sensorLine.addObserver(  obs  ) ;
        	}
         	if( sensor instanceof MagnetometerSensor){
        		MagnetometerSensor sensorMagneto = (MagnetometerSensor) sensor;
         		ISensorObserver<IMagnetometerSensorData> obs = new SensorObserver<IMagnetometerSensorData>(this,outEnvView);
        //		println( "avatar add observer to  "  + sensorMagneto.getDefStringRep() );
        		sensorMagneto.addObserver(  obs  ) ;
        	}
    		if( sensor instanceof ImpactSensor){
    			ImpactSensor sensorImpact = (ImpactSensor) sensor;
    			ISensorObserver<IImpactSensorData> obs = new SensorObserver<IImpactSensorData>(this,outEnvView);
    	//		println( "avatar add observer to  "  + sensorMagneto.getDefStringRep() );
    			sensorImpact.addObserver(  obs  ) ;
    		}
    	}		
    }	
    
 
	/* 
	* ------------------------------------------------------------
	* APPLICATION ACTIONS
	* ------------------------------------------------------------
	*/
	/* 
	* ------------------------------------------------------------
	* QUEUE  
	* ------------------------------------------------------------
	*/
	    protected void getMsgFromInputQueue(){
//	    	println( " %%%% getMsgFromInputQueue" ); 
	    	QActorMessage msg = mysupport.getMsgFromQueue(); //blocking
//	    	println( " %%%% getMsgFromInputQueue continues with " + msg );
	    	this.currentMessage = msg;
	    }
  }

