/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.roverconsole;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Roverconsole extends AbstractRoverconsole { 
	public Roverconsole(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
