/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.radardevicelogic;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Radardevicelogic extends AbstractRadardevicelogic { 
	public Radardevicelogic(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
