/* Generated by AN DISI Unibo */ 
package it.unibo.avatar;
import it.unibo.iot.executors.baseRobot.IBaseRobot;
import it.unibo.iot.models.commands.baseRobot.BaseRobotLeft;
import it.unibo.iot.models.commands.baseRobot.BaseRobotRight;
import it.unibo.iot.models.commands.baseRobot.BaseRobotStop;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactor.robot.RobotSysKb;
import it.unibo.qactors.QActorContext;

//
public class Avatar extends AbstractAvatar { 
	public Avatar(String actorId, QActorContext myCtx, IOutputEnvView outEnvView ) throws Exception{
		super(actorId,myCtx,outEnvView ,it.unibo.qactors.QActorUtils.robotBase );
	}
	@Override
	protected void doJob() throws Exception {
		IBaseRobot robot = it.unibo.qactor.robot.RobotSysKb.robotBase;
		println(getName() + " Avatar doJob  BaseRobotRight"  );
		robot.execute(new BaseRobotRight(RobotSysKb.SPEED_MEDIUM));
		this.delay(1500);
		println(getName() + " Avatar doJob  BaseRobotLeft"  );
		robot.execute(new BaseRobotLeft(RobotSysKb.SPEED_MEDIUM));
		this.delay(1500);
		println(getName() + " Avatar doJob  BaseRobotStop"  );
		robot.execute(new BaseRobotStop(RobotSysKb.SPEED_LOW));
 		println(getName() + " Avatar doJob ends "  );
 		super.doJob(); 
	} 
}
