/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.led017;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Led017 extends AbstractLed017 { 
	public Led017(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
