/* Generated by AN DISI Unibo */ 
package it.unibo.ctxBlsRaspOOp;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxBlsRaspOOp  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxblsraspoop", "./srcMore/it/unibo/ctxBlsRaspOOp/blsraspoop2017.pl", 
		"./srcMore/it/unibo/ctxBlsRaspOOp/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
   		//if( ctx.getEnv() == null){ ctx.terminateQActorSystem(); }
} 	
}
