/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.button;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Button extends AbstractButton { 
	public Button(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	
 	
}
