/* Generated by AN DISI Unibo */ 
package it.unibo.roverplanned;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

//
public class Roverplanned extends AbstractRoverplanned { 
	public Roverplanned(String actorId, QActorContext myCtx, IOutputEnvView outEnvView ) throws Exception{
		super(actorId,myCtx,outEnvView ,it.unibo.qactors.QActorUtils.robotBase );
	}
}
