/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qastepper;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.is.interfaces.protocols.IConnInteraction;
import it.unibo.qactors.QActorContext;

public class Qastepper extends AbstractQastepper { 
	protected IConnInteraction conn;
	
	public Qastepper(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public void startStepperPyhton(){
		try {
			println("Qastepper startStepperPyhton "  );
//			Process pPython =  
			Runtime.getRuntime().exec("sudo python stepper.py");
 		} catch (Exception e) {
 			e.printStackTrace();
		}		
	}
 }
