/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRoverControl;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxRoverControl  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxRoverControl";
	return QActorContext.initQActorSystem(
		"ctxrovercontrol", "./srcMore/it/unibo/ctxRoverControl/rovercontrol.pl", 
		"./srcMore/it/unibo/ctxRoverControl/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
