/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.controller017;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Controller017 extends AbstractController017 { 
	public Controller017(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
