/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.flashled;
import java.awt.Panel;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.myled.ILed;
import it.unibo.myled.LedWithGui;
import it.unibo.myled.LedWithRasp;
import it.unibo.qactors.QActorContext;

public class Flashled extends AbstractFlashled { 
	
	private  ILed led;
	
	public Flashled(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public void createGuiLed(int pinNum ){
		led = new LedWithGui();		
		outEnvView.getEnv().addPanel((Panel)led);
	}
	
	public void createPi4jLed(int pinNum ){
		led = new LedWithRasp(pinNum);
	}
	
	public void turnOn(){
		led.turnOn();
		//System.out.println("FLASH LED is " + (led.isOn()?"ON":"OFF"));
	}
	
	public void switchLedState(){
		led.ledSwitch();
		//System.out.println("FLASH LED is " + (led.isOn()?"ON":"OFF"));
		
	}
	
	public void turnOff(){
		led.turnOff();
		//System.out.println("FLASH LED is " + (led.isOn()?"ON":"OFF"));
	}
}
