/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qatestplans;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qatestplans extends AbstractQatestplans { 
	public Qatestplans(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	public String testReflectString(int n){
		println( "QQQQQQQQQQQQQQQQQQQQQQQ testReflectString " + n );
		return "test" + n;
	}
	
}
