/* Generated by AN DISI Unibo */ 
package it.unibo.rovermind;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.ActorTerminationMessage;
import it.unibo.qactors.QActorMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.contactEvent.interfaces.IEventItem;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.ActionReceiveTimed;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;


//REGENERATE AKKA: QActor instead QActorPlanned
public abstract class AbstractRovermind extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	//protected IMsgQueue mysupport ;  //defined in QActor
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction  action;
	
			protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
				return outEnvView;
			}
	
	
		public AbstractRovermind(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/rovermind/WorldTheory.pl",
			setTheEnv( outEnvView )  , "inist");		
			this.planFilePath = "./srcMore/it/unibo/rovermind/plans.txt";
			//Plan interpretation is done in Prolog
			//if(planFilePath != null) planUtils.buildPlanTable(planFilePath);
	 	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
	 		initSensorSystem();
			boolean res = inist();
			//println(getName() + " doJob " + res );
			QActorContext.terminateQActorSystem(this);
		} 
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/
	    public boolean inist() throws Exception{	//public to allow reflection
	    try{
	    	int nPlanIter = 0;
	    	//curPlanInExec =  "inist";
	    	boolean returnValue = suspendWork;		//MARCHH2017
	    while(true){
	    	curPlanInExec =  "inist";	//within while since it can be lost by switchlan
	    	nPlanIter++;
	    		temporaryStr = "\"rovermind STARTS\"";
	    		println( temporaryStr );  
	    		//parg = "actorOp(workWithUnity(\"127.0.0.1\"))"; //JUNE2017
	    		parg = "workWithUnity(\"127.0.0.1\")";
	    		//ex solveGoalReactive JUNE2017
	    		aar = actorOpExecuteReactive(parg,3600000,"","");
	    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    		if( aar.getInterrupted() ){
	    			curPlanInExec   = "inist";
	    			if( aar.getTimeRemained() <= 0 ) addRule("tout(actorOp,"+getName()+")");
	    			if( ! aar.getGoon() ) break;
	    		} 			
	    		else{
	    		//Store actorOpDone with the result
	    		 	String gg = "storeActorOpResult( X, Y )".replace("X", parg).replace("Y",aar.getResult() );
	    		 	//System.out.println("actorOpExecute gg=" + gg );
	    			 	 	pengine.solve(gg+".");			
	    		}
	    		
	    		if( ! planUtils.switchToPlan("someMove").getGoon() ) break;
	    		if( ! planUtils.switchToPlan("explore").getGoon() ) break;
	    		temporaryStr = "\"rovermind ENDS\"";
	    		println( temporaryStr );  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=inist WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean someMove() throws Exception{	//public to allow reflection
	    try{
	    	int nPlanIter = 0;
	    	//curPlanInExec =  "someMove";
	    	boolean returnValue = suspendWork;		//MARCHH2017
	    while(true){
	    	curPlanInExec =  "someMove";	//within while since it can be lost by switchlan
	    	nPlanIter++;
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??move(D,S,T,A)" )) != null ){
	    		//parg = "actorOp(moveVirtualActor(D,S,T,A))"; //JUNE2017
	    		parg = "moveVirtualActor(D,S,T,A)";
	    		parg = QActorUtils.substituteVars(guardVars,parg);
	    		//ex solveGoalReactive JUNE2017
	    		aar = actorOpExecuteReactive(parg,3600000,"alarm,sonarDetect","reactToAlarm,reactToObstacle");
	    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    		if( aar.getInterrupted() ){
	    			curPlanInExec   = "someMove";
	    			if( aar.getTimeRemained() <= 0 ) addRule("tout(actorOp,"+getName()+")");
	    			if( ! aar.getGoon() ) break;
	    		} 			
	    		else{
	    		//Store actorOpDone with the result
	    		 	String gg = "storeActorOpResult( X, Y )".replace("X", parg).replace("Y",aar.getResult() );
	    		 	//System.out.println("actorOpExecute gg=" + gg );
	    			 	 	pengine.solve(gg+".");			
	    		}
	    		
	    		}
	    		else{ println( "someMove ends" );
	    		//IF(curPlan.resume)»returnValue = continueWork;ENDIF»
	    		returnValue = continueWork;
	    		break;
	    		}if( planUtils.repeatPlan(nPlanIter,0).getGoon() ) continue;
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=someMove WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean explore() throws Exception{	//public to allow reflection
	    try{
	    	int nPlanIter = 0;
	    	//curPlanInExec =  "explore";
	    	boolean returnValue = suspendWork;		//MARCHH2017
	    while(true){
	    	curPlanInExec =  "explore";	//within while since it can be lost by switchlan
	    	nPlanIter++;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "usercmd(robotgui(CMD))","usercmd(robotgui(w(low)))", guardVars ).toString();
	    		emit( "usercmd", temporaryStr );
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "usercmd(robotgui(CMD))","usercmd(robotgui(d(low)))", guardVars ).toString();
	    		emit( "usercmd", temporaryStr );
	    		if( planUtils.repeatPlan(nPlanIter,8).getGoon() ) continue;
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=explore WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean reactToObstacle() throws Exception{	//public to allow reflection
	    try{
	    	int nPlanIter = 0;
	    	//curPlanInExec =  "reactToObstacle";
	    	boolean returnValue = suspendWork;		//MARCHH2017
	    while(true){
	    	curPlanInExec =  "reactToObstacle";	//within while since it can be lost by switchlan
	    	nPlanIter++;
	    		temporaryStr = "\"reactToObstacle\"";
	    		println( temporaryStr );  
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "usercmd(robotgui(CMD))","usercmd(robotgui(s(low)))", guardVars ).toString();
	    		emit( "usercmd", temporaryStr );
	    		//parg = "actorOp(moveVirtualActor(\"S\",30,1,0))"; //JUNE2017
	    		parg = "moveVirtualActor(\"S\",30,1,0)";
	    		//ex solveGoalReactive JUNE2017
	    		aar = actorOpExecuteReactive(parg,3600000,"alarm","reactToAlarm");
	    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    		if( aar.getInterrupted() ){
	    			curPlanInExec   = "reactToObstacle";
	    			if( aar.getTimeRemained() <= 0 ) addRule("tout(actorOp,"+getName()+")");
	    			if( ! aar.getGoon() ) break;
	    		} 			
	    		else{
	    		//Store actorOpDone with the result
	    		 	String gg = "storeActorOpResult( X, Y )".replace("X", parg).replace("Y",aar.getResult() );
	    		 	//System.out.println("actorOpExecute gg=" + gg );
	    			 	 	pengine.solve(gg+".");			
	    		}
	    		
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=reactToObstacle WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean reactToAlarm() throws Exception{	//public to allow reflection
	    try{
	    	int nPlanIter = 0;
	    	//curPlanInExec =  "reactToAlarm";
	    	boolean returnValue = suspendWork;		//MARCHH2017
	    while(true){
	    	curPlanInExec =  "reactToAlarm";	//within while since it can be lost by switchlan
	    	nPlanIter++;
	    		temporaryStr = "\"reactToAlarm\"";
	    		println( temporaryStr );  
	    		//onEvent
	    		if( currentEvent.getEventId().equals("alarm") ){
	    		 		//println("WARNING: variable substitution not yet implmented " ); 
	    		 		//playsound
	    		 		terminationEvId = "endPlay";
	    		 			 	aar = playSound("./audio/computer_process_info4.wav",ActionExecMode.asynch, terminationEvId, 2000,"" , "" ); 
	    		 				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    		 				if( aar.getInterrupted() ){
	    		 					curPlanInExec   = "reactToAlarm";
	    		 					if( aar.getTimeRemained() <= 0 ) addRule("tout(Sound,"+getName()+")");
	    		 					if( ! aar.getGoon() ) break;
	    		 				} 			
	    		 }
	    		//onEvent
	    		if( currentEvent.getEventId().equals("alarm") ){
	    		 		//println("WARNING: variable substitution not yet implmented " ); 
	    		 		//playsound
	    		 		terminationEvId = "endPlay";
	    		 			 	aar = playSound("./audio/any_commander3.wav",ActionExecMode.asynch, terminationEvId, 3000,"" , "" ); 
	    		 				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    		 				if( aar.getInterrupted() ){
	    		 					curPlanInExec   = "reactToAlarm";
	    		 					if( aar.getTimeRemained() <= 0 ) addRule("tout(Sound,"+getName()+")");
	    		 					if( ! aar.getGoon() ) break;
	    		 				} 			
	    		 }
	    		//onEvent
	    		if( currentEvent.getEventId().equals("alarm") ){
	    		 		String parg = "actorOp(moveVirtualActor(\"H\",30,1,0))";
	    		 		/* ActorOp */
	    		 		parg =  updateVars( Term.createTerm("alarm(X)"), Term.createTerm("alarm(fire)"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 		if( parg != null ){
	    		 			aar = solveGoalReactive(parg,3600000,"","");
	    		 			//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    		 			if( aar.getInterrupted() ){
	    		 				curPlanInExec   = "reactToAlarm";
	    		 				if( aar.getTimeRemained() <= 0 ) addRule("tout(actorOp,"+getName()+")");
	    		 				if( ! aar.getGoon() ) break;
	    		 			} 			
	    		 		}
	    		 }
	    		//onEvent
	    		if( currentEvent.getEventId().equals("alarm") ){
	    		 		String parg="usercmd(robotgui(h(low)))";
	    		 		/* RaiseEvent */
	    		 		parg = updateVars(Term.createTerm("alarm(X)"),  Term.createTerm("alarm(fire)"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 		if( parg != null ) emit( "usercmd", parg );
	    		 }
	    		//onEvent
	    		if( currentEvent.getEventId().equals("alarm") ){
	    		 		String parg="usercontrol";
	    		 		/* EndPlan */
	    		 		parg =  updateVars( Term.createTerm("alarm(X)"),  Term.createTerm("alarm(usercontrol)"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 		if( parg != null ){
	    		 			 println( parg);
	    		 			//IF(curPlan.resume)»returnValue = continueWork;ENDIF»
	    		 			returnValue = continueWork;
	    		 			break;
	    		 		}					
	    		 }
	    		else{ //we should restore nPlanIter and curPlanInExec of the 'interrupted' plan ???
	    		returnValue = continueWork;
	    		}
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=reactToAlarm WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	    
	 
		/* 
		* ------------------------------------------------------------
		* APPLICATION ACTIONS
		* ------------------------------------------------------------
		*/
		/* 
		* ------------------------------------------------------------
		* QUEUE  
		* ------------------------------------------------------------
		*/
		    protected void getMsgFromInputQueue(){
	//	    	println( " %%%% getMsgFromInputQueue" ); 
		    	QActorMessage msg = mysupport.getMsgFromQueue(); //blocking
	//	    	println( " %%%% getMsgFromInputQueue continues with " + msg );
		    	this.currentMessage = msg;
		    }
	  }
	
