/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.radardevice;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Radardevice extends AbstractRadardevice { 
    protected  String pos      = null; //p(  angle  ) 
    protected  String distance = null; //d(  distance  )
    protected  String fused    = "none"; //p( distance,angle )
    
    public Radardevice(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
    
    public String fuseSensorData(   ){
        if( pos != null && distance != null){	//received both
        	fused = "p(DISTANCE,ANGLE)".replace("DISTANCE", distance).replaceAll("ANGLE", pos);
 //    		println( getName() + " fused= " + fused );
       	} 
		return fused;
     }// fuseSensorData
    
    public void storeDistanceData(  int data ){
    	println("storeDistanceData  : " + data);
    	distance = ""+data;
    }    
    public void storeDirectionData(  int data ){
    	println("storeDirectionData  : " + data);
    	pos = ""+data;
    } 

}
