/* Generated by AN DISI Unibo */ 
package it.unibo.ctxBlsRaspButton;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxBlsRaspButton  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxblsraspbutton", "./srcMore/it/unibo/ctxBlsRaspButton/blsraspbutton2017.pl", 
		"./srcMore/it/unibo/ctxBlsRaspButton/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
