/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qaled;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Panel;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qaled extends AbstractQaled { 
	private Panel pled = new Panel( );
	private boolean ledState = true;	//HORRIBLE

	public Qaled(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	public void createLedGui(){
 		outEnvView.getEnv().addPanel(pled);
		ledSwitch();
   	}	
	public void ledSwitch(){
		ledState = ! ledState;
 		pled.setSize( new Dimension(20,20) );	//invalidates the hierarchy
		if( ledState ) pled.setBackground(Color.green);	//on
		else pled.setBackground(Color.red);	//off
		memoLedState();
	}
	
	public void memoLedState(){
		String goal = "assign(ledState,"+ledState+")";
		solveGoal( goal );		
	}
	
}
