/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.timer;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Timer extends AbstractTimer { 
	public Timer(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
