/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.evsource;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evsource extends AbstractEvsource { 
	public Evsource(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
