/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.buttongui017;
import it.unibo.is.interfaces.IActivity;
import it.unibo.is.interfaces.IIntent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Buttongui017 extends AbstractButtongui017 implements IActivity{ 
	private int count = 1;
	public Buttongui017(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * Application code
 */
	public void createButton(){
		outEnvView.getEnv().addCmdPanel("btn", new String[]{"click"}, this);
	}

	@Override
	public void execAction(String cmd) {
		this.emit("click", "click("+ count++ +")");
 	}
	@Override
	public void execAction() { 	}
	@Override
	public void execAction(IIntent input) { 	}
	@Override
	public String execActionWithAnswer(String cmd) { 		return null;	}

}
