/* Generated by AN DISI Unibo */ 
package it.unibo.roverconsole;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.ActorTerminationMessage;
import it.unibo.qactors.QActorMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.contactEvent.interfaces.IEventItem;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.ActionReceiveTimed;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;


//REGENERATE AKKA: QActor instead QActorPlanned
public abstract class AbstractRoverconsole extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	//protected IMsgQueue mysupport ;  //defined in QActor
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction  action;
	
			protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
				return outEnvView;
			}
	
	
		public AbstractRoverconsole(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/roverconsole/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");		
			this.planFilePath = "./srcMore/it/unibo/roverconsole/plans.txt";
			//Plan interpretation is done in Prolog
			//if(planFilePath != null) planUtils.buildPlanTable(planFilePath);
	 	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
	 		initSensorSystem();
			boolean res = init();
			//println(getName() + " doJob " + res );
			QActorContext.terminateQActorSystem(this);
		} 
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/
	    public boolean init() throws Exception{	//public to allow reflection
	    try{
	    	int nPlanIter = 0;
	    	//curPlanInExec =  "init";
	    	boolean returnValue = suspendWork;		//MARCHH2017
	    while(true){
	    	curPlanInExec =  "init";	//within while since it can be lost by switchlan
	    	nPlanIter++;
	    		temporaryStr = "\"roverconsole STARTS\"";
	    		println( temporaryStr );  
	    		if( ! planUtils.switchToPlan("handlecommands").getGoon() ) break;
	    		temporaryStr = "\"roverconsole ENDS\"";
	    		println( temporaryStr );  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=init WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean handlecommands() throws Exception{	//public to allow reflection
	    try{
	    	int nPlanIter = 0;
	    	//curPlanInExec =  "handlecommands";
	    	boolean returnValue = suspendWork;		//MARCHH2017
	    while(true){
	    	curPlanInExec =  "handlecommands";	//within while since it can be lost by switchlan
	    	nPlanIter++;
	    		temporaryStr = "\"roverconsole waits for user commands\"";
	    		println( temporaryStr );  
	    		//senseEvent
	    		aar = planUtils.senseEvents( 100000,"inputcmd,usercmd","execInputCommand,execRobotCommand",
	    		"sonarDetect,alarm" , "handleobstacle,handleAlarm",ActionExecMode.synch );
	    		if( ! aar.getGoon() || aar.getTimeRemained() <= 0 ){
	    			//println("			WARNING: sense timeout");
	    			addRule("tout(senseevent,"+getName()+")");
	    		}
	    		if( planUtils.repeatPlan(nPlanIter,0).getGoon() ) continue;
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=handlecommands WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean execInputCommand() throws Exception{	//public to allow reflection
	    try{
	    	int nPlanIter = 0;
	    	//curPlanInExec =  "execInputCommand";
	    	boolean returnValue = suspendWork;		//MARCHH2017
	    while(true){
	    	curPlanInExec =  "execInputCommand";	//within while since it can be lost by switchlan
	    	nPlanIter++;
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??no_usercontrol" )) != null ){
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "alarm(X)","alarm(usercontrol)", guardVars ).toString();
	    		emit( "alarm", temporaryStr );
	    		}
	    		memoCurrentEvent( false );
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?moveToCmd(R)" )) != null ){
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "usercmd(robotgui(CMD))","usercmd(R)", guardVars ).toString();
	    		emit( "usercmd", temporaryStr );
	    		}
	    		//onEvent
	    		if( currentEvent.getEventId().equals("inputcmd") ){
	    		 		String parg = "actorOp(moveVirtualActor(D,S,T,A))";
	    		 		/* ActorOp */
	    		 		parg =  updateVars( Term.createTerm("usercmd(X)"), Term.createTerm("usercmd(executeInput(move(D,S,T,A)))"), 
	    		 			    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    		 		if( parg != null ){
	    		 			aar = solveGoalReactive(parg,3600000,"sonarDetect,alarm,inputcmd,usercmd","handleobstacle,handleAlarm,handleAnotherCommand,handleAnotherCommand");
	    		 			//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    		 			if( aar.getInterrupted() ){
	    		 				curPlanInExec   = "execInputCommand";
	    		 				if( aar.getTimeRemained() <= 0 ) addRule("tout(actorOp,"+getName()+")");
	    		 				if( ! aar.getGoon() ) break;
	    		 			} 			
	    		 		}
	    		 }
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=execInputCommand WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean execRobotCommand() throws Exception{	//public to allow reflection
	    try{
	    	int nPlanIter = 0;
	    	//curPlanInExec =  "execRobotCommand";
	    	boolean returnValue = suspendWork;		//MARCHH2017
	    while(true){
	    	curPlanInExec =  "execRobotCommand";	//within while since it can be lost by switchlan
	    	nPlanIter++;
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " ??no_usercontrol" )) != null ){
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "alarm(X)","alarm(user)", guardVars ).toString();
	    		emit( "alarm", temporaryStr );
	    		}
	    		memoCurrentEvent( false );
	    		if( (guardVars = QActorUtils.evalTheGuard(this, " !?cmdToMove(move(D,S,T,A))" )) != null ){
	    		//parg = "actorOp(moveVirtualActor(D,S,T,A))"; //JUNE2017
	    		parg = "moveVirtualActor(D,S,T,A)";
	    		parg = QActorUtils.substituteVars(guardVars,parg);
	    		//ex solveGoalReactive JUNE2017
	    		aar = actorOpExecuteReactive(parg,3600000,"sonarDetect,alarm,inputcmd,usercmd","handleobstacle,handleAlarm,handleAnotherCommand,handleAnotherCommand");
	    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    		if( aar.getInterrupted() ){
	    			curPlanInExec   = "execRobotCommand";
	    			if( aar.getTimeRemained() <= 0 ) addRule("tout(actorOp,"+getName()+")");
	    			if( ! aar.getGoon() ) break;
	    		} 			
	    		else{
	    		//Store actorOpDone with the result
	    		 	String gg = "storeActorOpResult( X, Y )".replace("X", parg).replace("Y",aar.getResult() );
	    		 	//System.out.println("actorOpExecute gg=" + gg );
	    			 	 	pengine.solve(gg+".");			
	    		}
	    		
	    		}
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=execRobotCommand WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean handleAnotherCommand() throws Exception{	//public to allow reflection
	    try{
	    	int nPlanIter = 0;
	    	//curPlanInExec =  "handleAnotherCommand";
	    	boolean returnValue = suspendWork;		//MARCHH2017
	    while(true){
	    	curPlanInExec =  "handleAnotherCommand";	//within while since it can be lost by switchlan
	    	nPlanIter++;
	    		//parg = "actorOp(moveVirtualActor(\"H\",10,1,0))"; //JUNE2017
	    		parg = "moveVirtualActor(\"H\",10,1,0)";
	    		//ex solveGoalReactive JUNE2017
	    		aar = actorOpExecuteReactive(parg,3600000,"","");
	    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    		if( aar.getInterrupted() ){
	    			curPlanInExec   = "handleAnotherCommand";
	    			if( aar.getTimeRemained() <= 0 ) addRule("tout(actorOp,"+getName()+")");
	    			if( ! aar.getGoon() ) break;
	    		} 			
	    		else{
	    		//Store actorOpDone with the result
	    		 	String gg = "storeActorOpResult( X, Y )".replace("X", parg).replace("Y",aar.getResult() );
	    		 	//System.out.println("actorOpExecute gg=" + gg );
	    			 	 	pengine.solve(gg+".");			
	    		}
	    		
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=handleAnotherCommand WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean handleobstacle() throws Exception{	//public to allow reflection
	    try{
	    	int nPlanIter = 0;
	    	//curPlanInExec =  "handleobstacle";
	    	boolean returnValue = suspendWork;		//MARCHH2017
	    while(true){
	    	curPlanInExec =  "handleobstacle";	//within while since it can be lost by switchlan
	    	nPlanIter++;
	    		temporaryStr = "\"Alert received from sonar! Sending back robot\"";
	    		println( temporaryStr );  
	    		//playsound
	    		terminationEvId = "endPlay";
	    			 	aar = playSound("./audio/computer_process_info4.wav",ActionExecMode.asynch, terminationEvId, 2000,"" , "" ); 
	    				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    				if( aar.getInterrupted() ){
	    					curPlanInExec   = "handleobstacle";
	    					if( aar.getTimeRemained() <= 0 ) addRule("tout(Sound,"+getName()+")");
	    					if( ! aar.getGoon() ) break;
	    				} 			
	    		//parg = "actorOp(moveVirtualActor(\"S\",30,1,0))"; //JUNE2017
	    		parg = "moveVirtualActor(\"S\",30,1,0)";
	    		//ex solveGoalReactive JUNE2017
	    		aar = actorOpExecuteReactive(parg,3600000,"alarm","handleAlarm");
	    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    		if( aar.getInterrupted() ){
	    			curPlanInExec   = "handleobstacle";
	    			if( aar.getTimeRemained() <= 0 ) addRule("tout(actorOp,"+getName()+")");
	    			if( ! aar.getGoon() ) break;
	    		} 			
	    		else{
	    		//Store actorOpDone with the result
	    		 	String gg = "storeActorOpResult( X, Y )".replace("X", parg).replace("Y",aar.getResult() );
	    		 	//System.out.println("actorOpExecute gg=" + gg );
	    			 	 	pengine.solve(gg+".");			
	    		}
	    		
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=handleobstacle WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    public boolean handleAlarm() throws Exception{	//public to allow reflection
	    try{
	    	int nPlanIter = 0;
	    	//curPlanInExec =  "handleAlarm";
	    	boolean returnValue = suspendWork;		//MARCHH2017
	    while(true){
	    	curPlanInExec =  "handleAlarm";	//within while since it can be lost by switchlan
	    	nPlanIter++;
	    		temporaryStr = "\"ALARM\"";
	    		println( temporaryStr );  
	    		//playsound
	    		terminationEvId = "endPlay";
	    			 	aar = playSound("./audio/illogical_most2.wav",ActionExecMode.asynch, terminationEvId, 2000,"" , "" ); 
	    				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    				if( aar.getInterrupted() ){
	    					curPlanInExec   = "handleAlarm";
	    					if( aar.getTimeRemained() <= 0 ) addRule("tout(Sound,"+getName()+")");
	    					if( ! aar.getGoon() ) break;
	    				} 			
	    		//parg = "actorOp(moveVirtualActor(\"H\",30,1,0))"; //JUNE2017
	    		parg = "moveVirtualActor(\"H\",30,1,0)";
	    		//ex solveGoalReactive JUNE2017
	    		aar = actorOpExecuteReactive(parg,3600000,"","");
	    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    		if( aar.getInterrupted() ){
	    			curPlanInExec   = "handleAlarm";
	    			if( aar.getTimeRemained() <= 0 ) addRule("tout(actorOp,"+getName()+")");
	    			if( ! aar.getGoon() ) break;
	    		} 			
	    		else{
	    		//Store actorOpDone with the result
	    		 	String gg = "storeActorOpResult( X, Y )".replace("X", parg).replace("Y",aar.getResult() );
	    		 	//System.out.println("actorOpExecute gg=" + gg );
	    			 	 	pengine.solve(gg+".");			
	    		}
	    		
	    		returnValue = continueWork;  
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	       //println( getName() + " plan=handleAlarm WARNING:" + e.getMessage() );
	       QActorContext.terminateQActorSystem(this); 
	       return false;  
	    }
	    }
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	    
	 
		/* 
		* ------------------------------------------------------------
		* APPLICATION ACTIONS
		* ------------------------------------------------------------
		*/
		/* 
		* ------------------------------------------------------------
		* QUEUE  
		* ------------------------------------------------------------
		*/
		    protected void getMsgFromInputQueue(){
	//	    	println( " %%%% getMsgFromInputQueue" ); 
		    	QActorMessage msg = mysupport.getMsgFromQueue(); //blocking
	//	    	println( " %%%% getMsgFromInputQueue continues with " + msg );
		    	this.currentMessage = msg;
		    }
	  }
	
