/* Generated by AN DISI Unibo */ 
package it.unibo.ctxBlsSimple2017;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxBlsSimple2017  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxblssimple2017", "./srcMore/it/unibo/ctxBlsSimple2017/blsanalysissimple2017.pl", 
		"./srcMore/it/unibo/ctxBlsSimple2017/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
