/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.radarguilogic;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Radarguilogic extends AbstractRadarguilogic { 
	public Radarguilogic(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	public void sendDataToGui( int distance, int angle ){
 		println( "	Radarguilogic TO DO: DISPLAY distance= "+distance + " angle="+angle );
	} 
	public String checkDistance( int distance, int angle ){
		println(this.getName() + "  checkDistance int "  +  distance );
 		if( distance < 40 ) return "near";
		else if( (distance > 40) && (distance < 60) ) return "proximity";
		else return "far";
	}
	public String checkDistance( String distance, String angle ){
		println(this.getName() + "  checkDistance String "  +  distance );
// 		if( distance < 40 ) return "near";
//		else if( (distance > 40) && (distance < 60) ) return "proximity";
//		else 
			return "far";
	}
}
