/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.testermqtt;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Testermqtt extends AbstractTestermqtt { 
	public Testermqtt(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
