/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qacontrol;
import it.unibo.is.interfaces.IActivity;
import it.unibo.is.interfaces.IIntent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qacontrol extends AbstractQacontrol implements IActivity{ 
	private int count = 1;
	public Qacontrol(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	public void createAButtonWithGui(){
		outEnvView.getEnv().addCmdPanel("btn", new String[]{"click"}, this);
		
	}
	@Override
	public void execAction(String cmd) {
		try {
 			//sendMsg("turn","qaled", QActorContext.dispatch, "switch(" + count++ + ")" );
			this.emit("local_click", "clicked("+count++ +")");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 		
	}
	@Override
	public void execAction() {
	}
	@Override
	public void execAction(IIntent input) {
	}
	@Override
	public String execActionWithAnswer(String cmd) {
		return null;
	}
}
