/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.radargui;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Radargui extends AbstractRadargui { 
	protected  RadarControl radarControl;

	public Radargui(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	public boolean activateGui(  ) throws Exception{
		   println(this.getName() + " activateGui "   );
		   radarControl = new RadarControl(myCtx, outEnvView );
		   return true;
	}
		public void sendMsgDataToGui(  ){
			sendEDataToGui( currentMessage.msgContent() );
	  	}//sendMsgDataToGui
		
		public void sendEventDataToGui(  ){
			sendEDataToGui( currentEvent.getMsg() );
	  	}//sendMsgDataToGui

		public void sendDataToGui( int distance, int angle ){
//			println(this.getName() + "  sendEDataToGui int "   );
			radarControl.update( ""+distance,""+angle );
		} 
		public void sendEDataToGui( String data ){
	 		if( data.startsWith("'")) data = data.replaceAll("'", "");
			Struct posTerm = (Struct) Term.createTerm(data);
//			println(this.getName() + "  update GUI with " + posTerm );
			String dist  = ""+posTerm.getArg(0);
			String theta = ""+posTerm.getArg(1);
			radarControl.update( dist,theta );
	 	}//sendEDataToGui
		
		public String checkDistance( int distance, int angle ){
//			println(this.getName() + "  checkDistance "  +  distance );
			if( distance < 40 ) return "near";
			else if( (distance > 40) && (distance < 60) ) return "proximity";
			else return "far";
		}
}
