/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.button017;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Button017 extends AbstractButton017 { 
	public Button017(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
