/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRadarTfCe16;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxRadarTfCe16  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxradartfce16", "./srcMore/it/unibo/ctxRadarTfCe16/sonarsensor.pl", 
		"./srcMore/it/unibo/ctxRadarTfCe16/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
